import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getSortedPostsData } from '../lib/posts'

////////////////////////
//////////////////////// Typyescript 
// import { GetStaticPaths } from 'next'
// 
// export const getStaticPaths: GetStaticPaths = async () => {
//   // ...
// }
////////////////////////
///////////////////// Once!! build time called.
export async function getStaticProps(){ 
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}
////////////////////////
//////////////////////// Each!! request time called.
// function Page({ data }) {
//   // Render data...
// }
// // This gets called on every request
// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`https://.../data`)
//   const data = await res.json()
// 
//   // Pass data to the page via props
//   return { props: { data } }
// } 
// export default Page
////////////////////////
//////////////////// React hook for data fetching, Next.js
//import useSWR from 'swr'
//
//function Profile() {
//  const { data, error } = useSWR('/api/user', fetch)
//
//  if (error) return <div>failed to load</div>
//  if (!data) return <div>loading...</div>
//  return <div>hello {data.name}!</div>
//}
/////////////////////////////////////
export default function Home({ allPostsData }) { 
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/products.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js!
        </h1>

        <p className={styles.description}>
          editing..
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <section >
            <h2 >Blog</h2>
            <ul >
              {allPostsData.map(({id, date, title}) => (
              <li  key={id}>
                ({id}) {title} - {date}
              </li>
              ))}
            </ul>
  
          </section>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://simpledoers.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/products.svg" alt="Simple Logo" width={200} height={40} />
          </span>
        </a>
      </footer>
    </div>
  )
}
