import Head from 'next/head'
import Image from 'next/image'
import { Layout } from 'react'
import styles from '../styles/Home.module.css'
import { getSortedPostsData } from '../lib/posts'
export async function getStaticProps(){
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}
export default function Home({ allPostsData }) { 
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/products.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js!
        </h1>

        <p className={styles.description}>
          editing..
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <section >
            <h2 >Blog</h2>
            <ul >
              {allPostsData.map(({id, date, title}) => (
              <li  key={id}>
                ({id}) {title} - {date}
              </li>
              ))}
            </ul>
  
          </section>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://simpledoers.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/products.svg" alt="Simple Logo" width={200} height={40} />
          </span>
        </a>
      </footer>
    </div>
  )
}
